name: ci

on: [push, pull_request]

jobs:
  analyze:
    name: "Analyze dart code"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
      - name: "Install dependencies"
        run: |
          flutter pub get
          (cd demo && flutter pub get)
      - name: "Analyze Dart code"
        run: flutter analyze . --fatal-infos
      - name: "Validate Dart formatting"
        run: |
          flutter format .
          ./.github/workflows/scripts/validate-formatting.sh
