name: Deploy Demo

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy-for-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Build demo app for web
        working-directory: demo/
        run: flutter build web --release

      - name: Deploy demo app to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: demo/build/web # The folder the action should deploy.
          TARGET_FOLDER: demo/  # Target folder within gh-pages branch
          CLEAN: true # Automatically remove deleted files from the deploy branch